# Generated by Django 5.1.2 on 2024-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='From',
            new_name='from_location',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='To',
            new_name='to_location',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Train',
        ),
        migrations.AddField(
            model_name='details',
            name='train',
            field=models.IntegerField(default=0),
        ),
    ]
