# Generated by Django 5.1.2 on 2024-10-14 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_from_details_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='details',
            name='message',
            field=models.CharField(default='No message', max_length=1000),
        ),
    ]
