# Generated by Django 5.1.2 on 2024-10-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_savedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='train',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='savedetails',
            old_name='train',
            new_name='age',
        ),
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedetails',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
